## Importing the libraries

In [68]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [67]:
dataset = pd.read_csv('health_insurance.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
age = X[:, 0]
print(age)
print(X)
print(y)

[19 18 28 ... 18 21 61]
[[19 'female' 27.9 0 'yes' 'southwest']
 [18 'male' 33.77 1 'no' 'southeast']
 [28 'male' 33.0 3 'no' 'southeast']
 ...
 [18 'female' 36.85 0 'no' 'southeast']
 [21 'female' 25.8 0 'no' 'southwest']
 [61 'female' 29.07 0 'yes' 'northwest']]
[16884.924   1725.5523  4449.462  ...  1629.8335  2007.945  29141.3603]
[19 18 28 ... 18 21 61]
[[19 'female' 27.9 0 'yes' 'southwest']
 [18 'male' 33.77 1 'no' 'southeast']
 [28 'male' 33.0 3 'no' 'southeast']
 ...
 [18 'female' 36.85 0 'no' 'southeast']
 [21 'female' 25.8 0 'no' 'southwest']
 [61 'female' 29.07 0 'yes' 'northwest']]
[16884.924   1725.5523  4449.462  ...  1629.8335  2007.945  29141.3603]


## Encode Categorical Data



In [69]:
# encoding sex and smoker column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 1] = le.fit_transform(X[:,1])
X[:, 4] = le.fit_transform(X[:,4])

## Encoding the Region column

In [70]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [5])], remainder='passthrough')
X = np.array(ct.fit_transform(X))



## Splitting the dataset into Training set and Test set

In [71]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the model

In [72]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## Predicting the Test set results

In [80]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision = 2)

[[0.0 0.0 0.0 1.0 37 1 34.1 4 1]
 [0.0 0.0 1.0 0.0 18 1 34.43 0 0]
 [1.0 0.0 0.0 0.0 23 0 36.67 2 1]]


## Making a single prediction

> Predict a health insurance charges for a person with age = 55, sex = female, bmi = 30, 0 children, smoker - no and region = southwest  








In [83]:
print(regressor.predict([[0,0,0,1,55,1,30,0,0]]))

[11426.93]


## Getting the final linear regression equatin wuth the values of the coefficients

In [84]:
print(regressor.coef_)
print(regressor.intercept_)

[ 4.84e+02  2.24e+02 -4.29e+02 -2.78e+02  2.54e+02 -1.55e+01  3.36e+02
  4.37e+02  2.36e+04]
-12311.913605650474
